# Generated by Django 5.1.6 on 2025-05-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobilePhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100, unique=True)),
                ('ram', models.CharField(max_length=10)),
                ('storage', models.CharField(max_length=10)),
                ('price_range', models.CharField(max_length=50)),
                ('image_url', models.URLField()),
                ('rating', models.FloatField()),
                ('review_count', models.IntegerField()),
                ('specs', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-rating'],
            },
        ),
    ]
